fix auth
adevinta/vulcan-ui pull request #63
Opened 2023-10-03 14:27 UTC by jesusfcr

- Upgrade vue to latest 2 version
- Add target dev to dockerfile for development
- Redirect to login in case of 401/403

2023-10-04 09:10 UTC, seilagamo commented on Dockerfile
> +ENV TEAMS_CRUD=true
Why are you setting this as true?

2023-10-04 09:21 UTC, jesusfcr commented on Dockerfile
> +ENV TEAMS_CRUD=true
Good question, this is related to `envsub -s dollar-basic config.json dist/config.json` in package.json. 
Here I m setting a default for that env variable in order to the envsub command to generate a valid json.
When starting the dev container we don't run run.sh where this value is set up.

I added a comment.

2023-10-04 14:57 UTC, jesusfcr commented on Dockerfile
> +ENV TEAMS_CRUD=true
Also, I moved the envsub from package.json to the docker cmd to not interfere with the local usage.

2023-10-05 14:05 UTC, seilagamo requested changes

2023-10-05 14:18 UTC, jesusfcr commented on src/report/report.vue
> +          var redirectTo: string = window.location.toString().split("#")[0];
done, thanks

2023-10-05 14:18 UTC, jesusfcr commented on src/report/report.vue
> +      var re = err.response;
done, thanks

2023-10-05 14:45 UTC, seilagamo approved these changes
LGTM

2023-10-05 14:52 UTC, merged