Allow to edit recipients
adevinta/vulcan-ui pull request #65
Opened 2023-10-10 13:28 UTC by jesusfcr

2023-10-16 13:39 UTC, manelmontilla commented
Apart from some minor comments I would use the typed recipients API instead of the untyped one, I created a PR [here]( https://github.com/adevinta/vulcan-ui/pull/66) to modify the code to do so. If you agree you can just merge that PR into this one.

2023-10-16 13:39 UTC, manelmontilla requested changes

2023-10-16 13:39 UTC, manelmontilla commented on src/teams/home/home.vue
> +                  <b-input v-model="recipients" type="textarea" rows="5" placeholder="emails to receive notifications"></b-input>
I would include brief instructions about the expected format of the list of emails. So I would
s/emails to receive notifications/list of emails to receive notifications (one per line)

2023-10-16 13:39 UTC, manelmontilla commented on src/teams/home/home.vue
> +      const rec = this.recipients.split(/[ ,\n]+/).filter((e) => e.trim().length > 0);
I would allow only one separator: `\n` in this case.

2023-10-18 07:47 UTC, jesusfcr commented on src/teams/home/home.vue
> +                  <b-input v-model="recipients" type="textarea" rows="5" placeholder="emails to receive notifications"></b-input>
done

2023-10-18 07:48 UTC, jesusfcr commented on src/teams/home/home.vue
> +      const rec = this.recipients.split(/[ ,\n]+/).filter((e) => e.trim().length > 0);
done, also I added email validation as the api accepts anything

2023-10-20 06:29 UTC, manelmontilla approved these changes
LGTM

2023-10-20 06:54 UTC, merged