feat: improve error messages when creating a Jira ticket
adevinta/vulcan-ui pull request #69
Opened 2024-03-25 09:14 UTC by seilagamo

Hide the most technical errors under a generic message and show the others.

2024-04-04 12:23 UTC, jesusfcr requested changes

2024-04-04 12:23 UTC, jesusfcr commented on src/report/createTicketForm/createTicketForm.vue
> +        const message = this.ManageError(data.code, data.error);
I think ManageError expects data, not data.error

```
createTicketForm.vue:186 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'message')
    at t.ManageError (createTicketForm.vue:186:41)
    at createTicketForm.vue:151:30
```

2024-04-10 14:57 UTC, seilagamo commented on src/report/createTicketForm/createTicketForm.vue
> +        const message = this.ManageError(data.code, data.error);
Fixed in ecadd658a0d89ab188e4cb1e6603e4aa2d1765b5

2024-04-10 15:29 UTC, jesusfcr approved these changes
LGTM

2024-04-11 06:01 UTC, merged